"USE CLIENT";

IMPORT REACT FROM "REACT";

EXPORT DEFAULT FUNCTION HOME() {
  RETURN (
    <MAIN STYLE={{ PADDING: "2REM", MAXWIDTH: 700, MARGIN: "40PX AUTO", FONTFAMILY: "SANS-SERIF" }}>
      <H1>WELCOME TO VRINDA DOC SEARCH!</H1>
      <P>
        🎉 YOUR APPLICATION IS NOW DEPLOYED ON VERCEL AND READY FOR USE.<BR />
        <B>BACKEND:</B> CONNECTED TO CONVEX.<BR />
        <B>GOOGLE DRIVE SYNC AND GEMINI AI INTEGRATION</B> ENVIRONMENT VARIABLES ARE SET UP.
      </P>

      <H3>GOOGLE APPS SCRIPT URLS & SHEET ID:</H3>
      <UL>
        <LI>
          <B>APP SCRIPT API URL:</B><BR />
          <CODE>VITE_APP_SCRIPT_URL=HTTPS://SCRIPT.GOOGLE.COM/MACROS/S/AKFYCBZQ7-DRXEX5DBCCAXFSQDGJUBDAWKTIHOMDZ1PLACDKNRPKKFBO5ZNLVNTYN7LICZZ_MQ/EXEC</CODE>
        </LI>
        <LI>
          <B>GOOGLE SHEET ID:</B><BR />
          <CODE>VITE_GOOGLE_SHEET_ID=1FUHU5FB5Z77AQ4CAIK4ZYBQ-DPGJF0XLZEDSXIGT9M8</CODE>
        </LI>
        <LI>
          <B>ALTERNATE GOOGLE DRIVE SCRIPT URL:</B><BR />
          <CODE>HTTPS://SCRIPT.GOOGLE.COM/MACROS/S/AKFYCBY6XBPUA7XDJIBINBG8-CMBV1IG7HY5-BUKQ6Q4OVSJFBDXZ3JDKYK08Y9PUI4S2CIZ7A/EXEC</CODE>
        </LI>
      </UL>

      <H3>GOOGLE GEMINI AI KEY</H3>
      <CODE>AIZASYCHAQZJOAJQK9OZ5OSMPCTWBTVPGDWDKXQ</CODE>

      <HR />
      <P>
        {/* NEXT: REPLACE THIS COMPONENT WITH YOUR ACTUAL DOC SEARCH UI, DATA FETCHERS, AND FEATURES.
        YOU CAN USE FETCH TO CONNECT TO YOUR GOOGLE APPS SCRIPT API OR CONVEX BACKEND HERE! */}
      </P>
    </MAIN>
  );
}
